

service: postgressql

frameworkVersion: "=1.57.0"

provider:
  name: aws
  stage: dev
  region: us-west-2

resources:
  Resources:
    nsgCloudDB:
      Type: "AWS::RDS::DBInstance"
      Properties:
        AvailabilityZone: us-west-2a
        AllocatedStorage: "100"
        DBInstanceClass: db.t2.micro
        DBName: "nsgCloudDB"
        DBInstanceIdentifier: "nsgCloudDB"
        Engine: postgres
        Iops: "1000"
        MasterUserPassword: ${env:DB_PWD}
        MasterUsername: ${env:DB_USER}
        Port: 5432
        DBSubnetGroupName: default-vpc-0538b50f1bd3cfd82

  Outputs:
    nsgCloudDBUrl:
      Value: !Join
       - ':'
       - - "https://"
         - !GetAtt nsgCloudDB.Endpoint.Address
         - !GetAtt nsgCloudDB.Endpoint.Port
      Export:
        Name: nsgCloudDBUrl
